"""Shared DSL components for Rules and Practices."""

from .conditions import (
    ConditionType,
    Condition,
    EvaluationContext,
    evaluate_condition,
    evaluate_conditions,
)

from .triggers import (
    ScheduleInterval,
    EventType,
    Cadence,
    Schedule,
    Event,
    Trigger,
    should_schedule_fire,
    should_event_fire,
    next_fire_time,
)

from .effects import (
    EffectTarget,
    EffectOperator,
    Effect,
    EffectContext,
    EffectResult,
    apply_effect,
    apply_effects,
)

from .actions import (
    ActionType,
    TaskTemplate,
    PriorityTemplate,
    TaskSpec,
    PrioritySpec,
    MoveSpec,
    DeleteSpec,
    CollateSpec,
    CreateAction,
    MoveAction,
    DeleteAction,
    CollateAction,
    CollateTarget,
    ActionContext,
    expand_template,
    parse_due_date,
    execute_create_action,
    execute_move_action,
    execute_delete_action,
    execute_collate_action,
    PracticeAction,
    PracticeConfig,
)

__all__ = [
    # Conditions
    "ConditionType",
    "Condition",
    "EvaluationContext",
    "evaluate_condition",
    "evaluate_conditions",
    # Triggers
    "ScheduleInterval",
    "EventType",
    "Cadence",
    "Schedule",
    "Event",
    "Trigger",
    "should_schedule_fire",
    "should_event_fire",
    "next_fire_time",
    # Effects
    "EffectTarget",
    "EffectOperator",
    "Effect",
    "EffectContext",
    "EffectResult",
    "apply_effect",
    "apply_effects",
    # Actions
    "ActionType",
    "TaskTemplate",
    "PriorityTemplate",
    "TaskSpec",
    "PrioritySpec",
    "MoveSpec",
    "DeleteSpec",
    "CollateSpec",
    "CreateAction",
    "MoveAction",
    "DeleteAction",
    "CollateAction",
    "CollateTarget",
    "ActionContext",
    "expand_template",
    "parse_due_date",
    "execute_create_action",
    "execute_move_action",
    "execute_delete_action",
    "execute_collate_action",
    "PracticeAction",
    "PracticeConfig",
]
