"""
Lightweight dataclasses for Practice-based triggers.

These are used for inline trigger configuration within Practices,
replacing the old standalone Trigger entity model.
"""

from dataclasses import dataclass, field
from enum import StrEnum
import json
from typing import Any


class ScheduleInterval(StrEnum):
    """Supported schedule intervals for Practice triggers."""
    DAILY = "daily"
    WEEKDAYS = "weekdays"
    WEEKLY = "weekly"
    TWICE_DAILY = "2x_daily"


class TriggerEventType(StrEnum):
    """Types of events that can fire a Practice trigger."""
    SCHEDULE = "schedule"
    TASK_COMPLETED = "task_completed"
    PRIORITY_COMPLETED = "priority_completed"


@dataclass
class TriggerEvent:
    """Event configuration for a Practice trigger."""
    type: TriggerEventType
    params: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {"type": self.type.value, "params": self.params}

    @classmethod
    def from_dict(cls, data: dict) -> "TriggerEvent":
        return cls(
            type=TriggerEventType(data["type"]),
            params=data.get("params", {}),
        )


@dataclass
class TaskTemplate:
    """Template for tasks generated by a Practice trigger."""
    name_pattern: str
    notes_pattern: str | None = None
    due_date_offset: str | None = None  # e.g., "+1d", "end_of_day"
    tags: list[str] = field(default_factory=list)
    priority_id: str | None = None  # Override, usually inherits from Practice
    assign_to_creator: bool = False

    def to_dict(self) -> dict:
        return {
            "name_pattern": self.name_pattern,
            "notes_pattern": self.notes_pattern,
            "due_date_offset": self.due_date_offset,
            "tags": self.tags,
            "priority_id": self.priority_id,
            "assign_to_creator": self.assign_to_creator,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "TaskTemplate":
        return cls(
            name_pattern=data.get("name_pattern", ""),
            notes_pattern=data.get("notes_pattern"),
            due_date_offset=data.get("due_date_offset"),
            tags=data.get("tags", []),
            priority_id=data.get("priority_id"),
            assign_to_creator=data.get("assign_to_creator", False),
        )


@dataclass
class CollateConfig:
    """Configuration for task collation (batching) by a Practice trigger."""
    source_tag: str | None = None
    source_priority_id: str | None = None
    batch_name_pattern: str = "Batch for {{date}}"
    include_completed: bool = False
    mark_source_done: bool = False

    def to_dict(self) -> dict:
        return {
            "source_tag": self.source_tag,
            "source_priority_id": self.source_priority_id,
            "batch_name_pattern": self.batch_name_pattern,
            "include_completed": self.include_completed,
            "mark_source_done": self.mark_source_done,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "CollateConfig":
        return cls(
            source_tag=data.get("source_tag"),
            source_priority_id=data.get("source_priority_id"),
            batch_name_pattern=data.get("batch_name_pattern", "Batch for {{date}}"),
            include_completed=data.get("include_completed", False),
            mark_source_done=data.get("mark_source_done", False),
        )


@dataclass
class PracticeTrigger:
    """
    Inline trigger configuration for a Practice.

    This replaces the old standalone Trigger entity. Triggers are now
    embedded within Practices, not referenceable entities.
    """
    event: TriggerEvent
    task_template: TaskTemplate | None = None
    collate_config: CollateConfig | None = None
    conditions: list[dict] = field(default_factory=list)  # Reuses RuleCondition format
    enabled: bool = True

    def to_json(self) -> str:
        """Serialize to JSON for database storage."""
        data = {
            "event": self.event.to_dict(),
            "conditions": self.conditions,
            "enabled": self.enabled,
        }
        if self.task_template:
            data["task_template"] = self.task_template.to_dict()
        if self.collate_config:
            data["collate_config"] = self.collate_config.to_dict()
        return json.dumps(data)

    @classmethod
    def from_json(cls, json_str: str) -> "PracticeTrigger":
        """Deserialize from JSON database storage."""
        data = json.loads(json_str)
        return cls(
            event=TriggerEvent.from_dict(data["event"]),
            task_template=TaskTemplate.from_dict(data["task_template"]) if data.get("task_template") else None,
            collate_config=CollateConfig.from_dict(data["collate_config"]) if data.get("collate_config") else None,
            conditions=data.get("conditions", []),
            enabled=data.get("enabled", True),
        )

    @classmethod
    def from_json_or_none(cls, json_str: str | None) -> "PracticeTrigger | None":
        """Safely deserialize, returning None if input is None or empty."""
        if not json_str:
            return None
        try:
            return cls.from_json(json_str)
        except (json.JSONDecodeError, KeyError, TypeError):
            return None
